Repository ceems-dev/ceems, pull requests merged in 2025-07, with the labels that each got.

#377 Add systemd-less mode for Libvirt collector
  pkg/collector/cgroup.go
Labels: enhancement

#385 Add CONTRIBUTING.md file
  CONTRIBUTING.md
  README.md
  website/cspell.json
  website/docs/installation/containers.md
  website/docusaurus.config.ts
  website/md-link-check.json
  website/package.json
Labels: documentation

#388 Fix parsing nvidia-smi XML output
  pkg/collector/gpu.go
  pkg/collector/gpu_test.go
  pkg/collector/k8s.go
  pkg/collector/libvirt.go
  pkg/collector/slurm.go
  pkg/collector/slurm_test.go
  pkg/collector/testdata/nvidia-smi
Labels: bug
